
User.create(username: "Jack", password_digest: "1234")
User.create(username: "Jill", password_digest: "1234")
User.create(username: "Jeff", password_digest: "1234")
User.create(username: "Jake", password_digest: "1234")
User.create(username: "Jim", password_digest: "1234")
User.create(username: "Josh", password_digest: "1234")
User.create(username: "John", password_digest: "1234")
User.create(username: "Janet", password_digest: "1234")
User.create(username: "Julie", password_digest: "1234")
User.create(username: "Jeniffer", password_digest: "1234")

Post.create(user_id: 1, title: "Hard Times Hit Detroit", content: "This year in Detroit the time is now to get on the ball and create a new economic future")
Post.create(user_id: 2, title: "Hard Times Hit Detroit", content: "This year in Detroit the time is now to get on the ball and create a new economic future")
Post.create(user_id: 3, title: "Hard Times Hit Detroit", content: "This year in Detroit the time is now to get on the ball and create a new economic future")
Post.create(user_id: 4, title: "Hard Times Hit Detroit", content: "This year in Detroit the time is now to get on the ball and create a new economic future")
Post.create(user_id: 5, title: "Hard Times Hit Detroit", content: "This year in Detroit the time is now to get on the ball and create a new economic future")
Post.create(user_id: 6, title: "Hard Times Hit Detroit", content: "This year in Detroit the time is now to get on the ball and create a new economic future")
Post.create(user_id: 7, title: "Hard Times Hit Detroit", content: "This year in Detroit the time is now to get on the ball and create a new economic future")
Post.create(user_id: 8, title: "Hard Times Hit Detroit", content: "This year in Detroit the time is now to get on the ball and create a new economic future")
Post.create(user_id: 9, title: "Hard Times Hit Detroit", content: "This year in Detroit the time is now to get on the ball and create a new economic future")
Post.create(user_id: 10, title: "Hard Times Hit Detroit", content: "This year in Detroit the time is now to get on the ball and create a new economic future")